### ISSUE TITLE
Over 50 bots decryption error

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#312]
rust-mc-bot (not server!) getting. This is affecting 35f8ce7

```
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_47 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_39 disconnected
thread '<unnamed>' panicked at src/net.rs:203:9:
written != real_length, written: 301, real_length: 1815
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_22 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_36 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_43 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_42 disconnected
thread '<unnamed>' panicked at src/net.rs:203:9:
written != real_length, written: 308, real_length: 1859
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_23 disconnected
thread '<unnamed>' panicked at src/net.rs:203:9:
written != real_length, written: 315, real_length: 1903
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_38 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_40 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_34 disconnected
thread '<unnamed>' panicked at src/net.rs:203:9:
written != real_length, written: 322, real_length: 1947
thread '<unnamed>' panicked at src/net.rs:203:9:
written != real_length, written: 329, real_length: 1991
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_37 disconnected
decompression error: the data provided to a libdeflater *_decompress function call was invalid in some way (e.g. bad magic numbers, bad checksum)
Bot_41 disconnected
```

**Comment by TestingPlant** [comment]
I remember getting these errors while hyperion was still using monoio. We should try checking the compression implementation and rust-mc-bot's decompression too

**Comment by andrewgazelka** [comment]
@Eoghanmc22 going to ping you since you made `rust-mc-bot` but will look over it myself as well.

**Comment by andrewgazelka** [comment]
> I remember getting these errors while hyperion was still using monoio. We should try checking the compression implementation and rust-mc-bot's decompression too

I am wondering if it _is_ rust-mc-bot though. I know I could have thousands of bots pre-io-uring and no issues. but perhaps that was because it wasn't sending things fast enough? 🤷‍♂️ 🤔
