### ISSUE TITLE
kick players on game restart

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#507]

**Comment by andrewgazelka** [comment]
think this is just an issue when using docker-compose

**Comment by andrewgazelka** [comment]
nope

```

Caused by:
    Connection reset by peer (os error 54). Are you connected to a valid hyperion server? If you are connected to a vanilla server, hyperion-proxy will not work.
2024-10-25T12:35:00.676906Z  INFO ⏳ Binding to server... ~ Make sure the event server is running
thread 'tokio-runtime-worker' panicked at crates/hyperion-proxy/src/server_sender.rs:51:68:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-10-25T12:35:02.663066Z  WARN Error forwarding player packets to server: ReceiveClosed
thread 'tokio-runtime-worker' panicked at /Users/andrewgazelka/Projects/hyperion/crates/hyperion-proxy/src/player.rs:103:21:
Error forwarding player packets to server: ReceiveClosed
2024-10-25T12:35:02.663346Z  WARN Player packet reader task failed unexpectedly
2024-10-25T12:35:07.217997Z  INFO 🔗 Connected to server, accepting connections
```

**Comment by andrewgazelka** [comment]
done/fixed
